"""Chagall Bible illustrations configuration for download"""

CHAGALL_ARTWORKS = [
    {
        "filename": "chagall_women_of_bible_rachel_and_leah_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/women-of-bible-rachel-and-leah-marc-chagall.jpg",
        "title": "Women of Bible, Rachel and Leah by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/women-of-bible-rachel-and-leah-marc-chagall/",
    },
    {
        "filename": "chagall_women_of_bible_sarah_and_rebecca_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/women-of-bible-sarah-and-rebecca-marc-chagall.jpg",
        "title": "Women of Bible, Sarah and Rebecca by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/women-of-bible-sarah-and-rebecca-marc-chagall/",
    },
    {
        "filename": "chagall_untitled_the_cover_of_bible_1960_france_by_marc_ch.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/untitled-the-cover-of-bible-marc-chagall-1960-france.jpg",
        "title": "Untitled (The cover of Bible) (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/untitled-the-cover-of-bible-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_abraham_and_sarah_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/abraham-and-sarah-marc-chagall-1956-france.jpg",
        "title": "Abraham and Sarah (1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/abraham-and-sarah-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_abraham_approaching_sodom_with_three_angels_genesi.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/abraham-approaching-sodom-with-three-angels-genesis-xviii-16-marc-chagall-1956-france.jpg",
        "title": "Abraham approaching Sodom with Three Angels (Genesis , XVIII, 16) (1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/abraham-approaching-sodom-with-three-angels-genesis-xviii-16-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_boaz_wakes_up_and_see_ruth_at_his_feet_1960_france.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/boaz-wakes-up-and-see-ruth-at-his-feet-marc-chagall-1960-france.jpg",
        "title": "Boaz wakes up and see Ruth at his feet (1960; France) by Marc Chagall",
        "book": "Ruth",
        "page_url": "https://www.artchive.com/artwork/boaz-wakes-up-and-see-ruth-at-his-feet-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_elijah_is_taken_to_heaven_in_a_chariot_of_fire_to_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/elijah-is-taken-to-heaven-in-a-chariot-of-fire-to-his-disciple-elisha-marc-chagall-c1956-france.jpg",
        "title": "Elijah is taken to heaven in a chariot of fire, to his disciple Elisha (II Kings, II 0.9-12) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/elijah-is-taken-to-heaven-in-a-chariot-of-fire-to-his-disciple-elisha-ii-kings-ii-0-9-12-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_elijah_met_at_the_gate_of_zarephath_a_widow_trying.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/elijah-met-at-the-gate-of-zarephath-a-widow-trying-to-collect-firewood-marc-chagall-c1956-france.jpg",
        "title": "Elijah met at the gate of Zarephath a widow trying to collect firewood, which, on the order of the Lord nourish it during the famine (I Kings XVII, 1-10) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/elijah-met-at-the-gate-of-zarephath-a-widow-trying-to-collect-firewood-which-on-the-order-of-the-lord-nourish-it-during-the-famine-i-kings-xvii-1-10-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_elijah_on_the_top_of_mount_carmel_announced_the_im.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/elijah-on-the-top-of-mount-carmel-announced-the-impending-rain-befor-marc-chagall-c1956-france.jpg",
        "title": "Elijah, on the top of Mount Carmel, announced the impending rain before any single cloud in the sky appear (I Kings XVIII, 41-46) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/elijah-on-the-top-of-mount-carmel-announced-the-impending-rain-before-any-single-cloud-in-the-sky-appear-i-kings-xviii-41-46-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_elijah_resurrects_the_son_of_the_widow_of_zarephat.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/elijah-resurrects-the-son-of-the-widow-of-zarephath-i-kings-xvii-17-marc-chagall-c1956-france.jpg",
        "title": "Elijah resurrects the son of the widow of Zarephath (I Kings, XVII, 17-22) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/elijah-resurrects-the-son-of-the-widow-of-zarephath-i-kings-xvii-17-22-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_esther_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/esther-marc-chagall-1960-france.jpg",
        "title": "Esther (1960; France) by Marc Chagall",
        "book": "Esther",
        "page_url": "https://www.artchive.com/artwork/esther-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_in_rage_which_he_felt_to_the_idolatry_of_the_chose.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/in-rage-which-he-felt-to-the-idolatry-of-the-chosen-people-of-god-mos-marc-chagall-c1956-france.jpg",
        "title": "In rage which he felt to the idolatry of the chosen people of God, Moses broken the Tablets of the Law (Exodus, XXXII, 15-19) (c.1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/in-rage-which-he-felt-to-the-idolatry-of-the-chosen-people-of-god-moses-broken-the-tablets-of-the-law-exodus-xxxii-15-19-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_isaiah_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/isaiah-marc-chagall-1956-france.jpg",
        "title": "Isaiah (1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/isaiah-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_isaiah_s_oracle_on_the_ruins_of_babylon_isaiah_xii.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/isaiahs-oracle-on-the-ruins-of-babylon-isaiah-xiii-marc-chagall-c1956-france.jpg",
        "title": "Isaiah’s oracle on the ruins of Babylon (Isaiah XIII) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/isaiah-s-oracle-on-the-ruins-of-babylon-isaiah-xiii-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_isaiah_s_prayer_isaiah_lxiv_6_11_c_1956_france_by_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/isaiahs-prayer-isaiah-lxiv-6-11-marc-chagall-c1956-france.jpg",
        "title": "Isaiah’s Prayer (Isaiah LXIV, 6 11) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/isaiah-s-prayer-isaiah-lxiv-6-11-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_meeting_of_jacob_and_rachel_at_the_well_genesis_xx.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/meeting-of-jacob-and-rachel-at-the-well-genesis-xxix-7-10-marc-chagall-c1931-paris-france.jpg",
        "title": "Meeting of Jacob and Rachel at the well (Genesis XXIX, 7, 10) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/meeting-of-jacob-and-rachel-at-the-well-genesis-xxix-7-10-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_meeting_of_ruth_and_boaz_1960_france_by_marc_chaga.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/meeting-of-ruth-and-boaz-marc-chagall-1960-france.jpg",
        "title": "Meeting of Ruth and Boaz (1960; France) by Marc Chagall",
        "book": "Ruth",
        "page_url": "https://www.artchive.com/artwork/meeting-of-ruth-and-boaz-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_michal_saves_david_from_saul_1960_france_by_marc_c.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/michal-saves-david-from-saul-marc-chagall-1960-france.jpg",
        "title": "Michal saves David from Saul (1960; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/michal-saves-david-from-saul-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_miriam_sister_of_moses_dances_with_her_friends_to_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/miriam-sister-of-moses-dances-with-her-friends-to-celebrate-the-de-marc-chagall-c1934-paris-france.jpg",
        "title": "Miriam, sister of Moses, dances with her \u200b\u200bfriends to celebrate the deliverance of Israel (Exodus, XV,19-21) (c.1934; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/miriam-sister-of-moses-dances-with-her-friends-to-celebrate-the-deliverance-of-israel-exodus-xv-19-21-marc-chagall-c-1934-paris-france/",
    },
    {
        "filename": "chagall_song_of_songs_v_c_1965_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/song-of-songs-v-marc-chagall-c1965-france-6.jpg",
        "title": "Song of Songs V (c.1965; France) by Marc Chagall",
        "book": "Song_of_Songs",
        "page_url": "https://www.artchive.com/artwork/song-of-songs-v-marc-chagall-c-1965-france/",
    },
    {
        "filename": "chagall_the_sacrifice_offered_by_elijah_is_consumed_by_the.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/05/the-sacrifice-offered-by-elijah-is-consumed-by-the-fire-from-the-lord-marc-chagall-c1956-france.jpg",
        "title": "The sacrifice offered by Elijah is consumed by the fire from the Lord (I Kings XVIII, 36-38) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/the-sacrifice-offered-by-elijah-is-consumed-by-the-fire-from-the-lord-i-kings-xviii-36-38-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_abraham_is_going_to_sacrifice_his_son_according_to.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/abraham-is-going-to-sacrifice-his-son-according-to-the-order-of-god-g-marc-chagall-c1956-france.jpg",
        "title": "Abraham is going to sacrifice his son according to the order of God (Genesis, XXII, 9 14) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/abraham-is-going-to-sacrifice-his-son-according-to-the-order-of-god-genesis-xxii-9-14-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_abraham_weeping_for_sarah_genesis_xiii_1_1956_fran.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/abraham-weeping-for-sarah-genesis-xiii-1-marc-chagall-1956-france.jpg",
        "title": "Abraham Weeping for Sarah (Genesis, XIII, 1) (1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/abraham-weeping-for-sarah-genesis-xiii-1-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_absalom_riding_on_a_mule_is_caught_by_the_hair_on_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/absalom-riding-on-a-mule-is-caught-by-the-hair-on-the-branch-of-a-grea-marc-chagall-1956-france.jpg",
        "title": "Absalom riding on a mule is caught by the hair on the branch of a great oak. (Second Samuel 18:9) (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/absalom-riding-on-a-mule-is-caught-by-the-hair-on-the-branch-of-a-great-oak-second-samuel-18-9-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_by_beating_the_philistines_saul_killed_himself_by_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/by-beating-the-philistines-saul-killed-himself-by-his-own-sword-i-sa-marc-chagall-c1956-france.jpg",
        "title": "By beating the Philistines, Saul killed himself by his own sword (I Samuel, XXXI, 2 6)) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/by-beating-the-philistines-saul-killed-himself-by-his-own-sword-i-samuel-xxxi-2-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_cain_and_abel_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/cain-and-abel-marc-chagall-1960-france.jpg",
        "title": "Cain and Abel (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/cain-and-abel-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_eve_is_cursed_by_god_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/eve-is-cursed-by-god-marc-chagall-1960-france.jpg",
        "title": "Eve is cursed by God (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/eve-is-cursed-by-god-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_jacob_blessed_two_sons_of_joseph_despite_joseph_he.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jacob-blessed-two-sons-of-joseph-despite-joseph-he-raises-his-right-marc-chagall-c1956-france.jpg",
        "title": "Jacob blessed two sons of Joseph. Despite Joseph, he raises his right hand on the head of the younger, Ephraim, to whom he predicted a more glorious posterity than his older brother Manasseh (Genesis, xlviii, 14-21) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/jacob-blessed-two-sons-of-joseph-despite-joseph-he-raises-his-right-hand-on-the-head-of-the-younger-ephraim-to-whom-he-predicted-a-more-glorious-posterity-than-his-older-brother-manasseh-genesis-xlviii-14-21-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jacob_having_recognized_the_tunic_of_joseph_that_h.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jacob-having-recognized-the-tunic-of-joseph-that-his-son-reported-to-marc-chagall-c1956-france.jpg",
        "title": "Jacob, having recognized the tunic of Joseph that his son reported to him tinged with blood, think that he is dead and abandons himself in his grief (Genesis XXXVII, 31-35) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/jacob-having-recognized-the-tunic-of-joseph-that-his-son-reported-to-him-tinged-with-blood-think-that-he-is-dead-and-abandons-himself-in-his-grief-genesis-xxxvii-31-35-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jacob_leaves_his_country_and_his_family_to_go_to_e.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jacob-leaves-his-country-and-his-family-to-go-to-egypt-genesis-xlvi-marc-chagall-c1956-france.jpg",
        "title": "Jacob leaves his country and his family to go to Egypt (Genesis XLVI, 5 7) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/jacob-leaves-his-country-and-his-family-to-go-to-egypt-genesis-xlvi-5-7-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jacob_sees_in_a_dream_a_ladder_touching_the_sky_in.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jacob-sees-in-a-dream-a-ladder-touching-the-sky-in-which-the-angels-o-marc-chagall-c1956-france.jpg",
        "title": "Jacob sees in a dream a ladder touching the sky, in which the angels of God ascending and descending (Genesis, XXVIII, 14) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/jacob-sees-in-a-dream-a-ladder-touching-the-sky-in-which-the-angels-of-god-ascending-and-descending-genesis-xxviii-14-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_ruth_at_the_feet_of_boaz_1960_france_by_marc_chaga.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/ruth-at-the-feet-of-boaz-marc-chagall-1960-france.jpg",
        "title": "Ruth at the feet of Boaz (1960; France) by Marc Chagall",
        "book": "Ruth",
        "page_url": "https://www.artchive.com/artwork/ruth-at-the-feet-of-boaz-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_ruth_gleaning_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/ruth-gleaning-marc-chagall-1960-france.jpg",
        "title": "Ruth gleaning (1960; France) by Marc Chagall",
        "book": "Ruth",
        "page_url": "https://www.artchive.com/artwork/ruth-gleaning-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_samson_kills_a_young_lion_judges_xiv_5_6_c_1956_fr.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/samson-kills-a-young-lion-judges-xiv-5-6-marc-chagall-c1956-france.jpg",
        "title": "Samson kills a young lion (Judges, XIV, 5 6) (c.1956; France) by Marc Chagall",
        "book": "Judges",
        "page_url": "https://www.artchive.com/artwork/samson-kills-a-young-lion-judges-xiv-5-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_samuel_is_pouring_anointing_oil_to_saul_s_head_in_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/samuel-is-pouring-anointing-oil-to-sauls-head-in-sign-of-coronation-h-marc-chagall-c1956-france.jpg",
        "title": "Samuel is pouring anointing oil to Saul’s head in sign of coronation him as King of Israel  (I Samuel, IX, 27; XX, I) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/samuel-is-pouring-anointing-oil-to-saul-s-head-in-sign-of-coronation-him-as-king-of-israel-i-samuel-ix-27-xx-i-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_sarah_and_abimelech_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/sarah-and-abimelech-marc-chagall-1960-france.jpg",
        "title": "Sarah and Abimelech (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/sarah-and-abimelech-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_sarah_and_angels_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/sarah-and-angels-marc-chagall-1960-france.jpg",
        "title": "Sarah and angels (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/sarah-and-angels-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_adam_and_eve_expelled_from_paradise_land_1960_fran.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/adam-and-eve-expelled-from-paradise-land-marc-chagall-1960-france.jpg",
        "title": "Adam and Eve expelled from Paradise Land (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/adam-and-eve-expelled-from-paradise-land-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_adam_and_eve_with_the_forbidden_fruit_1960_france_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/adam-and-eve-with-the-forbidden-fruit-marc-chagall-1960-france.jpg",
        "title": "Adam and Eve with the forbidden fruit (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/adam-and-eve-with-the-forbidden-fruit-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_from_the_terrace_of_his_palace_david_sees_bathing_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/from-the-terrace-of-his-palace-david-sees-bathing-bathsheba-ii-samuel-marc-chagall-c1956-france.jpg",
        "title": "From the terrace of his palace David sees bathing Bathsheba (II Samuel, XI, 2-3) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/from-the-terrace-of-his-palace-david-sees-bathing-bathsheba-ii-samuel-xi-2-3-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_god_appears_to_moses_in_the_burning_bush_exodus_ii.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/god-appears-to-moses-in-the-burning-bush-exodus-iii-1-6-marc-chagall-c1956-france.jpg",
        "title": "God appears to Moses in the burning bush (Exodus, III, 1 6) (c.1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/god-appears-to-moses-in-the-burning-bush-exodus-iii-1-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_god_appears_to_solomon_in_a_dream_and_he_asked_him.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/god-appears-to-solomon-in-a-dream-and-he-asked-him-for-wisdom-i-kings-marc-chagall-c1956-france.jpg",
        "title": "God appears to Solomon in a dream and he asked Him for wisdom (I Kings, III, 5 9) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/god-appears-to-solomon-in-a-dream-and-he-asked-him-for-wisdom-i-kings-iii-5-9-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jacob_wrestling_with_the_angel_genesis_xxxii_24_30.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jacob-wrestling-with-the-angel-genesis-xxxii-24-30-marc-chagall-c1931-paris-france.jpg",
        "title": "Jacob wrestling with the angel (Genesis, XXXII, 24 30) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/jacob-wrestling-with-the-angel-genesis-xxxii-24-30-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_jeremiah_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jeremiah-marc-chagall-1956-france.jpg",
        "title": "Jeremiah (1956; France) by Marc Chagall",
        "book": "Jeremiah",
        "page_url": "https://www.artchive.com/artwork/jeremiah-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_moses_and_his_brother_come_to_pharaoh_and_claim_th.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-and-his-brother-come-to-pharaoh-and-claim-the-freedom-for-the-pe-marc-chagall-c1931-paris-france.jpg",
        "title": "Moses and his brother come to Pharaoh and claim the freedom for the people of Israel (Exodus, V, 1-4) (c.1931; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-and-his-brother-come-to-pharaoh-and-claim-the-freedom-for-the-people-of-israel-exodus-v-1-4-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_moses_casts_his_stick_that_transformed_into_a_snak.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-casts-his-stick-that-transformed-into-a-snake-on-the-orders-of-t-marc-chagall-c1931-paris-france.jpg",
        "title": "Moses casts his stick that transformed into a snake on the orders of the Lord, that referred to Aaron and Moses, when they had visited Pharaoh (Exodus, IV, 1-5, VII, 8-13) (c.1931; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-casts-his-stick-that-transformed-into-a-snake-on-the-orders-of-the-lord-that-referred-to-aaron-and-moses-when-they-had-visited-pharaoh-exodus-iv-1-5-vii-8-13-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_self_portrait_with_a_palette_1955_france_by_marc_c.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/self-portrait-with-a-palette-marc-chagall-1955-france.jpg",
        "title": "Self Portrait with a Palette (1955; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/self-portrait-with-a-palette-marc-chagall-1955-france/",
    },
    {
        "filename": "chagall_the_face_of_israel_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-face-of-israel-marc-chagall-1960-france.jpg",
        "title": "The Face of Israel (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/the-face-of-israel-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_after_the_flood_noah_offering_a_sacrifice_to_god_g.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/after-the-flood-noah-offering-a-sacrifice-to-god-genesis-viii-20-22-marc-chagall-c1931-paris-france.jpg",
        "title": "After the Flood Noah offering a sacrifice to God (Genesis VIII, 20 22) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/after-the-flood-noah-offering-a-sacrifice-to-god-genesis-viii-20-22-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_ahasuerus_sends_vasthi_away_1960_france_by_marc_ch.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/ahasuerus-sends-vasthi-away-marc-chagall-1960-france.jpg",
        "title": "Ahasuerus sends Vasthi away (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/ahasuerus-sends-vasthi-away-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_circumcision_prescribed_by_god_to_abraham_genesis_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/circumcision-prescribed-by-god-to-abraham-genesis-xvii-10-marc-chagall-c1956-france.jpg",
        "title": "Circumcision prescribed by God to Abraham (Genesis, XVII, 10) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/circumcision-prescribed-by-god-to-abraham-genesis-xvii-10-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_god_creates_man_and_gives_him_the_breath_of_life_g.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/god-creates-man-and-gives-him-the-breath-of-life-genesis-ii-7-marc-chagall-c1956-france.jpg",
        "title": "God creates Man and gives him the breath of life (Genesis II, 7) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/god-creates-man-and-gives-him-the-breath-of-life-genesis-ii-7-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jeremiah_received_gift_of_the_prophecy_jeremiah_i_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jeremiah-received-gift-of-the-prophecy-jeremiah-i-4-10-marc-chagall-c1956-france.jpg",
        "title": "Jeremiah received Gift of the prophecy (Jeremiah, I, 4 10) (c.1956; France) by Marc Chagall",
        "book": "Jeremiah",
        "page_url": "https://www.artchive.com/artwork/jeremiah-received-gift-of-the-prophecy-jeremiah-i-4-10-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jeremiah_thrown_into_a_prison_by_the_people_of_kin.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jeremiah-thrown-into-a-prison-by-the-people-of-king-zedekiah-jeremiah-marc-chagall-c1956-france.jpg",
        "title": "Jeremiah thrown into a prison by the people of King Zedekiah (Jeremiah, XXXVIII, 4 6) (c.1956; France) by Marc Chagall",
        "book": "Jeremiah",
        "page_url": "https://www.artchive.com/artwork/jeremiah-thrown-into-a-prison-by-the-people-of-king-zedekiah-jeremiah-xxxviii-4-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jerusalem_has_been_freed_from_babylon_according_to.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jerusalem-has-been-freed-from-babylon-according-to-the-prophecy-of-is-marc-chagall-c1956-france.jpg",
        "title": "Jerusalem has been freed from Babylon, according to the prophecy of Isaiah (Isaiah, XIV, 1 7) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/jerusalem-has-been-freed-from-babylon-according-to-the-prophecy-of-isaiah-isaiah-xiv-1-7-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_jerusalem_was_taken_by_nebuchadnezzar_as_the_proph.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/jerusalem-was-taken-by-nebuchadnezzar-as-the-prophecy-of-jeremiah-jer-marc-chagall-c1956-france.jpg",
        "title": "Jerusalem was taken by Nebuchadnezzar as the prophecy of Jeremiah (Jeremiah, XXI, 4 7) (c.1956; France) by Marc Chagall",
        "book": "Jeremiah",
        "page_url": "https://www.artchive.com/artwork/jerusalem-was-taken-by-nebuchadnezzar-as-the-prophecy-of-jeremiah-jeremiah-xxi-4-7-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_job_in_despair_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/job-in-despair-marc-chagall-1960-france.jpg",
        "title": "Job in despair (1960; France) by Marc Chagall",
        "book": "Job",
        "page_url": "https://www.artchive.com/artwork/job-in-despair-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_job_praying_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/job-praying-marc-chagall-1960-france.jpg",
        "title": "Job praying (1960; France) by Marc Chagall",
        "book": "Job",
        "page_url": "https://www.artchive.com/artwork/job-praying-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_moses_died_looking_to_the_promised_land_where_he_s.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-died-looking-to-the-promised-land-where-he-should-not-enter-de-marc-chagall-c1956-france.jpg",
        "title": "Moses died looking to the Promised Land, where he should not enter (Deuteronomy XXXIV, 1 5) (c.1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-died-looking-to-the-promised-land-where-he-should-not-enter-deuteronomy-xxxiv-1-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_moses_is_saved_from_the_waters_of_nile_by_pharaoh_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-is-saved-from-the-waters-of-nile-by-pharaohs-daughter-exodus-i-marc-chagall-c1956-france.jpg",
        "title": "Moses is saved from the waters of Nile by Pharaoh’s daughter (Exodus II, 5 6) (c.1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-is-saved-from-the-waters-of-nile-by-pharaoh-s-daughter-exodus-ii-5-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_moses_meets_in_the_desert_his_brother_aaron_who_ca.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-meets-in-the-desert-his-brother-aaron-who-came-towards-him-at-t-marc-chagall-c1931-paris-france.jpg",
        "title": "Moses meets in the desert his brother Aaron, who came towards him at the behest of God (Exodus, IV, 27-28) (c.1931; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-meets-in-the-desert-his-brother-aaron-who-came-towards-him-at-the-behest-of-god-exodus-iv-27-28-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_moses_on_the_order_of_the_lord_has_struck_the_rock.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-on-the-order-of-the-lord-has-struck-the-rock-in-horeb-and-spark-marc-chagall-c1934-paris-france.jpg",
        "title": "Moses, on the order of the Lord has struck the rock in Horeb and sparked a source (Exodus, xvii, 4-7) (c.1934; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/moses-on-the-order-of-the-lord-has-struck-the-rock-in-horeb-and-sparked-a-source-exodus-xvii-4-7-marc-chagall-c-1934-paris-france/",
    },
    {
        "filename": "chagall_the_forgiveness_of_god_is_announced_in_jerusalem_i.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-forgiveness-of-god-is-announced-in-jerusalem-isaiah-liv-6-10-marc-chagall-c1956-france.jpg",
        "title": "The Forgiveness of God is announced in Jerusalem (Isaiah LIV, 6 10) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/the-forgiveness-of-god-is-announced-in-jerusalem-isaiah-liv-6-10-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_the_vision_of_ezekiel_ezekiel_i_4_14_c_1956_france.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-vision-of-ezekiel-ezekiel-i-4-14-marc-chagall-c1956-france.jpg",
        "title": "The Vision of Ezekiel (Ezekiel, I, 4-14) (c.1956; France) by Marc Chagall",
        "book": "Ezekiel",
        "page_url": "https://www.artchive.com/artwork/the-vision-of-ezekiel-ezekiel-i-4-14-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_already_been_old_joshua_brings_together_the_israel.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/already-been-old-joshua-brings-together-the-israelites-and-recalls-o-marc-chagall-c1956-france.jpg",
        "title": "Already been old, Joshua brings together  the Israelites and recalls of the favor which the Lord has blessed (Judges, XXIII, 14-16) (c.1956; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/already-been-old-joshua-brings-together-the-israelites-and-recalls-of-the-favor-which-the-lord-has-blessed-judges-xxiii-14-16-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_an_angel_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/an-angel-marc-chagall-1956-france.jpg",
        "title": "An angel (1956; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/an-angel-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_angel_in_paradise_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/angel-in-paradise-marc-chagall-1956-france.jpg",
        "title": "Angel in Paradise (1956; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/angel-in-paradise-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_hagar_in_the_desert_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/hagar-in-the-desert-marc-chagall-1960-france.jpg",
        "title": "Hagar in the desert (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/hagar-in-the-desert-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_hannah_prays_to_the_lord_for_a_son_who_will_be_sam.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/hannah-prays-to-the-lord-for-a-son-who-will-be-samuel-i-samuel-i-9-marc-chagall-c1956-france.jpg",
        "title": "Hannah prays to the Lord for a son who will be Samuel (I Samuel, I, 9 11) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/hannah-prays-to-the-lord-for-a-son-who-will-be-samuel-i-samuel-i-9-11-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_happy_future_of_jerusalem_have_found_favor_with_go.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/happy-future-of-jerusalem-have-found-favor-with-god-isaiah-lxii-1-5-marc-chagall-c1956-france.jpg",
        "title": "Happy future of Jerusalem have found favor with God (Isaiah, LXII, 1 5) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/happy-future-of-jerusalem-have-found-favor-with-god-isaiah-lxii-1-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_having_become_the_favorite_the_pharaoh_joseph_gets.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/having-become-the-favorite-the-pharaoh-joseph-gets-his-brothers-come-marc-chagall-c1956-france.jpg",
        "title": "Having become the favorite the Pharaoh, Joseph gets his brothers come to Egypt requests food supplies for their country suffered from famine. He makes himself known to them and pardon them (Genesis XLV, 1-8) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/having-become-the-favorite-the-pharaoh-joseph-gets-his-brothers-come-to-egypt-requests-food-supplies-for-their-country-suffered-from-famine-he-makes-himself-known-to-them-and-pardon-them-genesis-xlv-1-8-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_having_heard_about_the_death_of_jonathan_his_close.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/having-heard-about-the-death-of-jonathan-his-closest-friend-which-ha-marc-chagall-c1956-france.jpg",
        "title": "Having heard about the death of Jonathan, his closest friend, which had been killed in battle against the Philistines, David cries and sings a mournful song (II Samuel, I, 17-27) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/having-heard-about-the-death-of-jonathan-his-closest-friend-which-had-been-killed-in-battle-against-the-philistines-david-cries-and-sings-a-mournful-song-ii-samuel-i-17-27-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_being_informed_about_absalom_s_death_which_has_bee.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/being-informed-about-absaloms-death-which-has-been-killed-by-joab-an-marc-chagall-c1956-france.jpg",
        "title": "Being informed about Absalom’s death, which has been killed by Joab and has been found hanging on the tree in the forest, David gives vent to his grief (Samuel II, XIX, 1-4) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/being-informed-about-absalom-s-death-which-has-been-killed-by-joab-and-has-been-found-hanging-on-the-tree-in-the-forest-david-gives-vent-to-his-grief-samuel-ii-xix-1-4-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_having_lingered_in_gaza_house_of_courtesan_and_wat.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/having-lingered-in-gaza-house-of-courtesan-and-watched-by-the-people-marc-chagall-c1956-france.jpg",
        "title": "Having lingered in Gaza house of courtesan, and watched by the people who wanted to kill him, Samson takes the gates of the city, the load them on his back and will place them on top of a mountain (Judges XVI, 1 – 3) (c.1956; France) by Marc Chagall",
        "book": "Judges",
        "page_url": "https://www.artchive.com/artwork/having-lingered-in-gaza-house-of-courtesan-and-watched-by-the-people-who-wanted-to-kill-him-samson-takes-the-gates-of-the-city-the-load-them-on-his-back-and-will-place-them-on-top-of-a-mountain-judges-xvi-1-3-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joseph_being_seventeen_years_old_goes_with_his_bro.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joseph-being-seventeen-years-old-goes-with-his-brothers-and-the-flock-marc-chagall-c1956-france.jpg",
        "title": "Joseph being seventeen years old, goes with his brothers and the flocks (Genesis XXXVII, 2) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/joseph-being-seventeen-years-old-goes-with-his-brothers-and-the-flocks-genesis-xxxvii-2-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joseph_explains_the_dreams_of_pharaoh_genesis_xli_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joseph-explains-the-dreams-of-pharaoh-genesis-xli-25-28-32-marc-chagall-c1956-france.jpg",
        "title": "Joseph explains the dreams of Pharaoh (Genesis XLI, 25 28 32) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/joseph-explains-the-dreams-of-pharaoh-genesis-xli-25-28-32-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joseph_explains_the_dreams_of_pharaoh_genesis_xli_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joseph-explains-the-dreams-of-pharaoh-genesis-xli-25-28-32-marc-chagall-1931-paris-france.jpg",
        "title": "Joseph explains the dreams of Pharaoh (Genesis XLI, 25 28 32) (1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/joseph-explains-the-dreams-of-pharaoh-genesis-xli-25-28-32-marc-chagall-1931-paris-france/",
    },
    {
        "filename": "chagall_joseph_is_attacked_and_robbed_by_his_brothers_gene.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joseph-is-attacked-and-robbed-by-his-brothers-genesis-xxxvii-23-24-marc-chagall-c1956-france.jpg",
        "title": "Joseph is attacked and robbed by his brothers (Genesis XXXVII, 23 24) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/joseph-is-attacked-and-robbed-by-his-brothers-genesis-xxxvii-23-24-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joshua_closes_the_book_of_law_that_he_has_just_rea.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joshua-closes-the-book-of-law-that-he-has-just-read-to-the-people-of-i-marc-chagall-c1956-france.jpg",
        "title": "Joshua closes the book of Law that he has just read to the people of Israel (Joshua, VIII, 33 35) (c.1956; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/joshua-closes-the-book-of-law-that-he-has-just-read-to-the-people-of-israel-joshua-viii-33-35-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joshua_is_delivering_the_five_kings_of_canaan_to_i.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joshua-is-delivering-the-five-kings-of-canaan-to-israels-hands-and-pr-marc-chagall-c1956-france.jpg",
        "title": "Joshua is delivering the five kings of Canaan to Israel’s hands and preparing them to death (Judges, X, 22-26) (c.1956; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/joshua-is-delivering-the-five-kings-of-canaan-to-israel-s-hands-and-preparing-them-to-death-judges-x-22-26-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joshua_moses_successor_as_head_of_israel_is_prepar.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joshua-moses-successor-as-head-of-israel-is-preparing-to-cross-the-j-marc-chagall-c1956-france.jpg",
        "title": "Joshua, Moses’ successor as head of Israel is preparing to cross the Jordan at the behest of the Lord (Joshua, I, 1-6) (c.1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/joshua-moses-successor-as-head-of-israel-is-preparing-to-cross-the-jordan-at-the-behest-of-the-lord-joshua-i-1-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_moses_received_the_tablets_of_law_1956_france_by_m.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-received-the-tablets-of-law-marc-chagall-1956-france.jpg",
        "title": "Moses received the Tablets of Law (1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-received-the-tablets-of-law-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_paradise_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/paradise-marc-chagall-1960-france.jpg",
        "title": "Paradise (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/paradise-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_paradise_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/paradise-marc-chagall-1960-france.jpg",
        "title": "Paradise (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/paradise-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_solomon_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/solomon-marc-chagall-1956-france.jpg",
        "title": "Solomon (1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/solomon-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_the_hebrews_adore_the_golden_calf_exodus_xxxii_7_1.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-hebrews-adore-the-golden-calf-exodus-xxxii-7-10-marc-chagall-c1934-paris-france.jpg",
        "title": "The Hebrews adore the golden calf (Exodus XXXII, 7, 10) (c.1934; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/the-hebrews-adore-the-golden-calf-exodus-xxxii-7-10-marc-chagall-c-1934-paris-france/",
    },
    {
        "filename": "chagall_the_israelites_go_over_jordan_following_of_the_ark.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-israelites-go-over-jordan-following-of-the-ark-of-the-covenant-tha-marc-chagall-c1956-france.jpg",
        "title": "The Israelites go over Jordan following of the Ark of the Covenant that is brought to them at the behest of Joshua (Joshua, III, 3-6) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/the-israelites-go-over-jordan-following-of-the-ark-of-the-covenant-that-is-brought-to-them-at-the-behest-of-joshua-joshua-iii-3-6-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_angel_with_a_sword_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/angel-with-a-sword-marc-chagall-1956-france.jpg",
        "title": "Angel with a sword (1956; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/angel-with-a-sword-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_creation_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/creation-marc-chagall-1960-france.jpg",
        "title": "Creation (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/creation-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_joshua_prostrates_himself_before_the_angel_sword_b.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joshua-prostrates-himself-before-the-angel-sword-bearer-chief-of-the-marc-chagall-c1956-france.jpg",
        "title": "Joshua prostrates himself before the angel sword-bearer, chief of the armies of the Lord (Joshua, V, 13-15) (c.1956; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/joshua-prostrates-himself-before-the-angel-sword-bearer-chief-of-the-armies-of-the-lord-joshua-v-13-15-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_joshua_receives_the_blessing_of_moses_deuteronomy_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/joshua-receives-the-blessing-of-moses-deuteronomy-xxxiv-9-marc-chagall-c1956-france.jpg",
        "title": "Joshua receives the blessing of Moses (Deuteronomy, XXXIV, 9) (c.1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/joshua-receives-the-blessing-of-moses-deuteronomy-xxxiv-9-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_josue_and_the_stone_of_sichem_c_1931_paris_france_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/josue-and-the-stone-of-sichem-marc-chagall-c1931-paris-france.jpg",
        "title": "Josue and the stone of Sichem (c.1931; Paris, France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/josue-and-the-stone-of-sichem-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_king_david_ii_samuel_vi_4_5_c_1956_france_by_marc_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/king-david-ii-samuel-vi-4-5-marc-chagall-c1956-france.jpg",
        "title": "King David (II Samuel, VI, 4 5) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/king-david-ii-samuel-vi-4-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_moses_receiving_the_tablets_of_the_law_from_god_on.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-receiving-the-tablets-of-the-law-from-god-on-mount-sinaiexodus-marc-chagall-c1934-paris-france.jpg",
        "title": "Moses  receiving the Tablets of the Law from God on mount Sinai(Exodus, XXIV, 15 18) (c.1934; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-receiving-the-tablets-of-the-law-from-god-on-mount-sinai-exodus-xxiv-15-18-marc-chagall-c-1934-paris-france/",
    },
    {
        "filename": "chagall_moses_spreads_the_darkness_over_egypt_exodus_ix_21.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-spreads-the-darkness-over-egypt-exodus-ix-21-23-marc-chagall-c1931-paris-france.jpg",
        "title": "Moses spreads the darkness over Egypt (Exodus, IX, 21 23) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/moses-spreads-the-darkness-over-egypt-exodus-ix-21-23-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_peace_and_glory_were_brought_to_jerusalem_with_the.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/peace-and-glory-were-brought-to-jerusalem-with-the-forgiveness-of-god-marc-chagall-c1956-france.jpg",
        "title": "Peace and Glory were brought to Jerusalem with the forgiveness of God (Isaiah LII, 1 7) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/peace-and-glory-were-brought-to-jerusalem-with-the-forgiveness-of-god-isaiah-lii-1-7-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_peace_and_the_further_reign_of_jerusalem_in_prophe.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/peace-and-the-further-reign-of-jerusalem-in-prophecy-of-isaiah-isaiah-marc-chagall-c1956-france.jpg",
        "title": "Peace and the further reign of Jerusalem in Prophecy of Isaiah (Isaiah, II, 1 5) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/peace-and-the-further-reign-of-jerusalem-in-prophecy-of-isaiah-isaiah-ii-1-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_solomon_is_proclaimed_a_king_of_israel_i_kings_i_3.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/solomon-is-proclaimed-a-king-of-israel-i-kings-i-32-40-marc-chagall-c1956-france.jpg",
        "title": "Solomon is proclaimed a King of Israel (I Kings, I, 32 40) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/solomon-is-proclaimed-a-king-of-israel-i-kings-i-32-40-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_solomon_on_the_throne_i_kings_x_18_20_c_1956_franc.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/solomon-on-the-throne-i-kings-x-18-20-marc-chagall-c1956-france.jpg",
        "title": "Solomon on the throne (I Kings, X, 18 20) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/solomon-on-the-throne-i-kings-x-18-20-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_solomon_praying_in_the_temple_in_presence_of_the_c.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/solomon-praying-in-the-temple-in-presence-of-the-congregation-of-israe-marc-chagall-c1956-france.jpg",
        "title": "Solomon praying in the temple in presence of the congregation of Israel  (I Kings, VIII, 23 30) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/solomon-praying-in-the-temple-in-presence-of-the-congregation-of-israel-i-kings-viii-23-30-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_tamar_beautiful_daughter_of_judah_1960_france_by_m.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/tamar-beautiful-daughter-of-judah-marc-chagall-1960-france.jpg",
        "title": "Tamar, beautiful daughter of Judah (1960; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/tamar-beautiful-daughter-of-judah-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_the_israelites_pass_the_red_sea_however_the_first_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-israelites-pass-the-red-sea-however-the-first-chariots-of-the-egy-marc-chagall-c1934-paris-france.jpg",
        "title": "The Israelites pass the Red Sea, however the first chariots of the Egyptian army are drowned (Exodus, XIV, 19-28) (c.1934; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/the-israelites-pass-the-red-sea-however-the-first-chariots-of-the-egyptian-army-are-drowned-exodus-xiv-19-28-marc-chagall-c-1934-paris-france/",
    },
    {
        "filename": "chagall_the_israelites_which_have_gone_from_egypt_with_ang.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-israelites-which-have-gone-from-egypt-with-angel-of-death-are-ea-marc-chagall-c1934-paris-france.jpg",
        "title": "The Israelites, which have gone from Egypt with Angel of death, are eating the Easter lamb (Exodus, XII, 11-14) (c.1934; Paris, France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/the-israelites-which-have-gone-from-egypt-with-angel-of-death-are-eating-the-easter-lamb-exodus-xii-11-14-marc-chagall-c-1934-paris-france/",
    },
    {
        "filename": "chagall_the_jacob_s_dream_1977_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-jacobs-dream-marc-chagall-1977-france.jpg",
        "title": "The Jacob’s Dream (1977; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/the-jacob-s-dream-marc-chagall-1977-france/",
    },
    {
        "filename": "chagall_the_young_samuel_the_priest_s_servant_heard_that_h.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-young-samuel-the-priests-servant-heard-that-he-is-called-by-go-marc-chagall-c1956-france.jpg",
        "title": "The young Samuel, the priest’s servant, heard, that he is called by God, Eli and he were sleeping in the bedroom of his master, (I Samuel, III, 1-4) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/the-young-samuel-the-priest-s-servant-heard-that-he-is-called-by-god-eli-and-he-were-sleeping-in-the-bedroom-of-his-master-i-samuel-iii-1-4-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_three_angels_visit_abraham_genesis_xviii_1_8_c_195.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/three-angels-visit-abraham-genesis-xviii-1-8-marc-chagall-c1956-france.jpg",
        "title": "Three angels visit Abraham (Genesis, XVIII, 1 8) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/three-angels-visit-abraham-genesis-xviii-1-8-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_title_page_angel_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/title-page-angel-marc-chagall-1956-france.jpg",
        "title": "Title page, Angel (1956; France) by Marc Chagall",
        "book": "General",
        "page_url": "https://www.artchive.com/artwork/title-page-angel-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_arrival_of_queen_sheba_to_jerusalem_i_kings_x_1_5_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/arrival-of-queen-sheba-to-jerusalem-i-kings-x-1-5-marc-chagall-c1956-france.jpg",
        "title": "Arrival of Queen Sheba to Jerusalem (I Kings, X, 1 5) (c.1956; France) by Marc Chagall",
        "book": "Kings",
        "page_url": "https://www.artchive.com/artwork/arrival-of-queen-sheba-to-jerusalem-i-kings-x-1-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_a_seraph_purify_the_lips_of_isaiah_with_a_hot_coal.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/a-seraph-purify-the-lips-of-isaiah-with-a-hot-coal-isaiah-vi-1-7-marc-chagall-c1956-france.jpg",
        "title": "A seraph purify the lips of Isaiah with a hot coal (Isaiah VI, 1 7) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/a-seraph-purify-the-lips-of-isaiah-with-a-hot-coal-isaiah-vi-1-7-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_lamentations_of_jeremiah_lamentations_iii_1_9_c_19.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/lamentations-of-jeremiah-lamentations-iii1-9-marc-chagall-c1956-france.jpg",
        "title": "Lamentations of Jeremiah (Lamentations III:1-9) (c.1956; France) by Marc Chagall",
        "book": "Jeremiah",
        "page_url": "https://www.artchive.com/artwork/lamentations-of-jeremiah-lamentations-iii-1-9-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_moses_with_the_tablets_of_the_law_1956_france_by_m.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-with-the-tablets-of-the-law-marc-chagall-1956-france.jpg",
        "title": "Moses with the Tablets of the Law (1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-with-the-tablets-of-the-law-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_moses_with_the_tablets_of_the_law_1956_france_by_m.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-with-the-tablets-of-the-law-marc-chagall-1956-france.jpg",
        "title": "Moses with the Tablets of the Law (1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-with-the-tablets-of-the-law-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_moses_with_the_tablets_of_the_law_1956_france_by_m.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/moses-with-the-tablets-of-the-law-marc-chagall-1956-france.jpg",
        "title": "Moses with the Tablets of the Law (1956; France) by Marc Chagall",
        "book": "Exodus",
        "page_url": "https://www.artchive.com/artwork/moses-with-the-tablets-of-the-law-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_the_judgement_of_solomon_i_kings_iii_16_27_c_1956_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-judgement-of-solomon-i-kings-iii-16-27-marc-chagall-c1956-france.jpg",
        "title": "The Judgement of Solomon (I Kings, III, 16 27) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/the-judgement-of-solomon-i-kings-iii-16-27-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_the_lord_appears_to_elijah_at_the_entrance_to_the_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-lord-appears-to-elijah-at-the-entrance-to-the-cave-in-which-he-too-marc-chagall-1956-france.jpg",
        "title": "The Lord appears to Elijah at the entrance to the cave in which he took refuge (I Kings, XIX, 9, 13) (1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/the-lord-appears-to-elijah-at-the-entrance-to-the-cave-in-which-he-took-refuge-i-kings-xix-9-13-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_under_the_walls_of_jericho_joshua_listens_god_s_or.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/under-the-walls-of-jericho-joshua-listens-gods-orders-which-requirin-marc-chagall-c1956-france.jpg",
        "title": "Under the walls of Jericho, Joshua listens God’s orders which requiring him to sound trumpets around the city (Joshua, VI, 3-5) (c.1956; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/under-the-walls-of-jericho-joshua-listens-god-s-orders-which-requiring-him-to-sound-trumpets-around-the-city-joshua-vi-3-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_david_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-marc-chagall-1956-france.jpg",
        "title": "David (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_david_and_absalom_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-and-absalom-marc-chagall-1956-france.jpg",
        "title": "David and Absalom (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-and-absalom-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_david_and_bathsheba_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-and-bathsheba-marc-chagall-1956-france.jpg",
        "title": "David and Bathsheba (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-and-bathsheba-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_david_and_bathsheba_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-and-bathsheba-marc-chagall-1956-france.jpg",
        "title": "David and Bathsheba (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-and-bathsheba-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_david_freed_from_all_of_his_enemies_sings_a_hymn_o.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-freed-from-all-of-his-enemies-sings-a-hymn-of-victory-to-the-lo-marc-chagall-c1956-france.jpg",
        "title": "David freed from all of his enemies, sings a hymn of victory to the Lord (II Samuel XXII) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-freed-from-all-of-his-enemies-sings-a-hymn-of-victory-to-the-lord-ii-samuel-xxii-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_lot_and_his_daughters_genesis_xix_31_35_c_1931_par.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/lot-and-his-daughters-genesis-xix-31-35-marc-chagall-c1931-paris-france.jpg",
        "title": "Lot and His Daughters (Genesis, XIX, 31 35) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/lot-and-his-daughters-genesis-xix-31-35-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_naomi_and_her_daughters_in_law_1960_france_by_marc.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/naomi-and-her-daughters-in-law-marc-chagall-1960-france.jpg",
        "title": "Naomi and her daughters-in-law (1960; France) by Marc Chagall",
        "book": "Ruth",
        "page_url": "https://www.artchive.com/artwork/naomi-and-her-daughters-in-law-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_near_gibeon_joshua_to_give_his_troops_time_to_gain.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/near-gibeon-joshua-to-give-his-troops-time-to-gain-the-victory-stops-marc-chagall-c1956-france.jpg",
        "title": "Near Gibeon Joshua, to give his troops time to gain the victory, stops the sun (Joshua X, 12-14) (c.1956; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/near-gibeon-joshua-to-give-his-troops-time-to-gain-the-victory-stops-the-sun-joshua-x-12-14-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_potiphar_s_wife_unsuccessfully_tries_to_seduce_jos.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/potiphars-wife-unsuccessfully-tries-to-seduce-joseph-genesis-xxxix-marc-chagall-c1956-france.jpg",
        "title": "Potiphar’s wife unsuccessfully tries to seduce Joseph (Genesis XXXIX, 7 9) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/potiphar-s-wife-unsuccessfully-tries-to-seduce-joseph-genesis-xxxix-7-9-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_prisoner_of_the_philistines_who_gouged_out_his_eye.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/prisoner-of-the-philistines-who-gouged-out-his-eyes-samson-whose-str-marc-chagall-c1956-france.jpg",
        "title": "Prisoner of the Philistines who gouged out his eyes, Samson, whose strength came back with his hair pushed back, knocks down the pillars of the house and will die with his enemies when the roof will fall (Judges XVI, 28-30) (c.1956; France) by Marc Chagall",
        "book": "Judges",
        "page_url": "https://www.artchive.com/artwork/prisoner-of-the-philistines-who-gouged-out-his-eyes-samson-whose-strength-came-back-with-his-hair-pushed-back-knocks-down-the-pillars-of-the-house-and-will-die-with-his-enemies-when-the-roof-will-fall-judges-xvi-28-30-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_the_ark_of_the_covenant_transported_to_jerusalem_p.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-ark-of-the-covenant-transported-to-jerusalem-preceded-by-david-da-marc-chagall-c1956-france.jpg",
        "title": "The Ark of the Covenant transported to Jerusalem, preceded by David dancing and playing the harp (II Samuel, VI, 1-5) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/the-ark-of-the-covenant-transported-to-jerusalem-preceded-by-david-dancing-and-playing-the-harp-ii-samuel-vi-1-5-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_the_man_guided_by_the_lord_the_right_way_isaiah_lv.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-man-guided-by-the-lord-the-right-way-isaiah-lviii-8-11-marc-chagall-c1956-france.jpg",
        "title": "The man guided by the Lord the right way (Isaiah, LVIII, 8 11) (c.1956; France) by Marc Chagall",
        "book": "Isaiah",
        "page_url": "https://www.artchive.com/artwork/the-man-guided-by-the-lord-the-right-way-isaiah-lviii-8-11-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_the_monument_on_the_tomb_of_rachel_on_the_path_eph.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-monument-on-the-tomb-of-rachel-on-the-path-ephra-genesis-xxxv-1-marc-chagall-c1931-paris-france.jpg",
        "title": "The monument on the tomb of Rachel, on the path Ephra (Genesis XXXV, 19 20) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/the-monument-on-the-tomb-of-rachel-on-the-path-ephra-genesis-xxxv-19-20-marc-chagall-c-1931-paris-france/",
    },
    {
        "filename": "chagall_bathsheba_reminds_david_of_his_promise_to_appoint_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/bathsheba-reminds-david-of-his-promise-to-appoint-their-son-solomon-as-marc-chagall-1956-france.jpg",
        "title": "Bathsheba reminds David of his promise to appoint their son Solomon as king of Israel after him (I Kings, I, 15-20) (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/bathsheba-reminds-david-of-his-promise-to-appoint-their-son-solomon-as-king-of-israel-after-him-i-kings-i-15-20-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_before_the_death_blind_isaac_bless_his_second_son_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/before-the-death-blind-isaac-bless-his-second-son-jacob-rebecca-tol-marc-chagall-1956-france.jpg",
        "title": "Before the death, blind Isaac bless his second son Jacob, Rebecca, told him to make it for his elder son, Esau (Genesis, XXVII, 26-29) (1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/before-the-death-blind-isaac-bless-his-second-son-jacob-rebecca-told-him-to-make-it-for-his-elder-son-esau-genesis-xxvii-26-29-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_being_asleep_in_the_desert_where_he_had_retired_to.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/being-asleep-in-the-desert-where-he-had-retired-to-wait-for-the-death-marc-chagall-c1956-france.jpg",
        "title": "Being asleep in the desert where he had retired to wait for the death, Elijah has been  awakened and cheered by an angel (I Kings, XIX, 5-8) (c.1956; France) by Marc Chagall",
        "book": "II_Kings",
        "page_url": "https://www.artchive.com/artwork/being-asleep-in-the-desert-where-he-had-retired-to-wait-for-the-death-elijah-has-been-awakened-and-cheered-by-an-angel-i-kings-xix-5-8-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_david_killed_a_lion_that_threatened_his_flock_i_sa.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-killed-a-lion-that-threatened-his-flock-i-samuel-xvii-34-36-marc-chagall-c1956-france.jpg",
        "title": "David killed a lion that threatened his flock (I Samuel, XVII, 34, 36) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-killed-a-lion-that-threatened-his-flock-i-samuel-xvii-34-36-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_david_on_his_throne_hosts_his_rebellious_son_absal.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-on-his-throne-hosts-his-rebellious-son-absalom-forgives-him-and-marc-chagall-c1956-france.jpg",
        "title": "David on his throne hosts his rebellious son Absalom, forgives him and kisses him (II Samuel, XIV, 28-33) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-on-his-throne-hosts-his-rebellious-son-absalom-forgives-him-and-kisses-him-ii-samuel-xiv-28-33-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_david_sings_accompanying_himself_in_the_harp_befor.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-sings-accompanying-himself-in-the-harp-before-saul-and-relieves-marc-chagall-c1956-france.jpg",
        "title": "David sings accompanying himself in the harp before Saul, and relieves his suffering (I Samuel, XVI, 19-23) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/david-sings-accompanying-himself-in-the-harp-before-saul-and-relieves-his-suffering-i-samuel-xvi-19-23-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_david_s_victory_over_goliath_i_samuel_xvii_48_51_c.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/davids-victory-over-goliath-i-samuel-xvii-48-51-marc-chagall-c1956-france.jpg",
        "title": "David’s victory over Goliath (I Samuel, XVII, 48, 51) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-s-victory-over-goliath-i-samuel-xvii-48-51-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_david_with_his_harp_1956_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-with-his-harp-marc-chagall-1956-france.jpg",
        "title": "David with his harp (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-with-his-harp-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_david_with_the_head_of_goliath_comes_to_saul_i_sam.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/david-with-the-head-of-goliath-comes-to-saul-i-samuel-xvii-55-58-marc-chagall-c1956-france.jpg",
        "title": "David with the Head of Goliath, comes to Saul (I Samuel, XVII, 55 58) (c.1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/david-with-the-head-of-goliath-comes-to-saul-i-samuel-xvii-55-58-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_deborah_the_prophetess_urges_barak_to_raise_an_arm.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/deborah-the-prophetess-urges-barak-to-raise-an-army-and-give-battle-to-marc-chagall-c1956-france.jpg",
        "title": "Deborah the prophetess urges Barak to raise an army and give battle to the army of Jabin (Judges IV, 4-9) (c.1956; France) by Marc Chagall",
        "book": "Judges",
        "page_url": "https://www.artchive.com/artwork/deborah-the-prophetess-urges-barak-to-raise-an-army-and-give-battle-to-the-army-of-jabin-judges-iv-4-9-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_delilah_cut_samson_s_hair_and_had_thus_deprived_hi.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/delilah-cut-samsons-hair-and-had-thus-deprived-him-his-superhuman-st-marc-chagall-c1956-france.jpg",
        "title": "Delilah cut Samson’s hair and, had thus deprived him his superhuman strength, he has fallen asleep on her lap and she is going to deliver him to Philistines who watch (Judges XVI, 15-18) (c.1956; France) by Marc Chagall",
        "book": "Judges",
        "page_url": "https://www.artchive.com/artwork/delilah-cut-samson-s-hair-and-had-thus-deprived-him-his-superhuman-strength-he-has-fallen-asleep-on-her-lap-and-she-is-going-to-deliver-him-to-philistines-who-watch-judges-xvi-15-18-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_prophet_daniel_with_lions_1956_france_by_marc_chag.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/prophet-daniel-with-lions-marc-chagall-1956-france.jpg",
        "title": "Prophet Daniel with lions (1956; France) by Marc Chagall",
        "book": "Daniel",
        "page_url": "https://www.artchive.com/artwork/prophet-daniel-with-lions-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_rachel_hides_her_father_s_household_gods_1960_fran.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/rachel-hides-her-fathers-household-gods-marc-chagall-1960-france.jpg",
        "title": "Rachel hides her father’s household gods (1960; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/rachel-hides-her-father-s-household-gods-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_song_of_songs_iii_1960_france_by_marc_chagall.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/song-of-songs-iii-marc-chagall-1960-france-7.jpg",
        "title": "Song of Songs III (1960; France) by Marc Chagall",
        "book": "Song_of_Songs",
        "page_url": "https://www.artchive.com/artwork/song-of-songs-iii-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_the_calling_of_ezekiel_ezekiel_ii_8x_iii_3_c_1956_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/the-calling-of-ezekiel-ezekiel-ii-8x-iii-3-marc-chagall-c1956-france.jpg",
        "title": "The calling of Ezekiel (Ezekiel, II, 8X, III, 3) (c.1956; France) by Marc Chagall",
        "book": "Ezekiel",
        "page_url": "https://www.artchive.com/artwork/the-calling-of-ezekiel-ezekiel-ii-8x-iii-3-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_aaron_in_front_of_the_golden_candlestick_with_seve.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/aaron-in-front-of-the-golden-candlestick-with-seven-branches-executed-marc-chagall-c1956-france.jpg",
        "title": "Aaron in front of the golden candlestick with seven branches, executed as prescribed by Lord (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/aaron-in-front-of-the-golden-candlestick-with-seven-branches-executed-as-prescribed-by-lord-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_driven_from_jerusalem_by_rebelled_again_absalom_da.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/driven-from-jerusalem-by-rebelled-again-absalom-david-barefoot-clim-marc-chagall-1956-france.jpg",
        "title": "Driven from Jerusalem by rebelled again Absalom, David, barefoot, climbed to the hill of Olives (1956; France) by Marc Chagall",
        "book": "I_Samuel",
        "page_url": "https://www.artchive.com/artwork/driven-from-jerusalem-by-rebelled-again-absalom-david-barefoot-climbed-to-the-hill-of-olives-marc-chagall-1956-france/",
    },
    {
        "filename": "chagall_manoah_and_his_wife_offering_a_sacrifice_saw_the_a.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/manoah-and-his-wife-offering-a-sacrifice-saw-the-angel-of-the-lord-f-marc-chagall-c1956-france.jpg",
        "title": "Manoah and his wife, offering a sacrifice, saw the angel of the Lord flying in the flame (Judges, XIII, 17-23) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/manoah-and-his-wife-offering-a-sacrifice-saw-the-angel-of-the-lord-flying-in-the-flame-judges-xiii-17-23-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_rahab_and_the_spies_of_jericho_1960_france_by_marc.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/rahab-and-the-spies-of-jericho-marc-chagall-1960-france.jpg",
        "title": "Rahab and the Spies of Jericho (1960; France) by Marc Chagall",
        "book": "Joshua",
        "page_url": "https://www.artchive.com/artwork/rahab-and-the-spies-of-jericho-marc-chagall-1960-france/",
    },
    {
        "filename": "chagall_rainbow_in_the_sky_a_sign_of_covenant_between_god_.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/rainbow-in-the-sky-a-sign-of-covenant-between-god-and-earth-genesis-marc-chagall-c1956-france.jpg",
        "title": "Rainbow in the sky, a sign of Covenant between God and Earth, (Genesis, IX, 8 17) (c.1956; France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/rainbow-in-the-sky-a-sign-of-covenant-between-god-and-earth-genesis-ix-8-17-marc-chagall-c-1956-france/",
    },
    {
        "filename": "chagall_rebecca_gives_drink_to_the_servant_of_abraham_whic.jpg",
        "url": "https://www.artchive.com/wp-content/uploads/2024/08/rebecca-gives-drink-to-the-servant-of-abraham-which-recognizes-the-br-marc-chagall-c1931-paris-france.jpg",
        "title": "Rebecca gives drink to the servant of Abraham, which recognizes the bride destined by God to Isaac, the son of his master (Genesis, XXIV, 12-15) (c.1931; Paris, France) by Marc Chagall",
        "book": "Genesis",
        "page_url": "https://www.artchive.com/artwork/rebecca-gives-drink-to-the-servant-of-abraham-which-recognizes-the-bride-destined-by-god-to-isaac-the-son-of-his-master-genesis-xxiv-12-15-marc-chagall-c-1931-paris-france/",
    },
]

ATTRIBUTION = """Marc Chagall Bible illustrations courtesy of artchive.com
Source: https://www.artchive.com/?s=chagall+bible"""
